from network3 import network

network.run(["s2"], True)
print("")
network.run(["s1"], True)
print("")
network.run(["s2"], True)
print("")
network.run(["s2"], True)
print("")
network.run(["s1", "s2"], True)
print("")
network.run(["s2"], True)
print("")
network.run(["s2"], True)
print("")
network.run(["s2"], True)
print("")
network.run(["s2"], True)
print("")
network.run(["s2"], True)
print("")
network.run(["s1", "s2"], True)
